# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0006_auto_20160717_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='feels',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'low'), (2, 'moderate'), (3, 'high'), (4, 'extreme')], default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='gore',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'unmarred dead'), (2, 'silhouetted dismemberment'), (3, 'dismemberment')], default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='sexual_intent',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'unintentional'), (2, 'mischievous'), (3, 'malicious(molestation)'), (4, 'extremley malicious(rape)')], default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='on_screen_intimacy',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'light kissing'), (2, 'deep kissing/grope'), (3, 'sex')], default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='profanity',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'mild'), (2, 'cencored'), (3, 'uncencored')], default=0),
        ),
    ]
