# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0011_show_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Series'),
        ),
    ]
