# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0012_auto_20160803_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeupload.Tag')),
            ],
        ),
    ]
