# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0015_auto_20160813_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_relation',
            name='show_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show'),
        ),
    ]
