# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0016_auto_20160813_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['english_title']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
        migrations.RenameField(
            model_name='tag_relation',
            old_name='show_id',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='tag_relation',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='tag_relation',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show'),
        ),
    ]
