# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0020_auto_20160821_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommendment',
            new_name='recommended',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show', unique=True),
        ),
        migrations.AlterField(
            model_name='tag_relation',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show'),
        ),
    ]
