# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0021_auto_20160821_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='show_id',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animeupload.Series'),
        ),
        migrations.AlterField(
            model_name='tag_relation',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show'),
        ),
    ]
