# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=200)),
                ('japanese_title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('total_episodes', models.IntegerField()),
                ('total_seasons', models.IntegerField(default=1)),
                ('ongoing', models.BooleanField(default=False)),
            ],
        ),
    ]
