# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.FileField(blank=True, default='images/fnf/fnf.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='show',
            name='nudity',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'underwear'), (2, 'cencored'), (3, 'butt'), (4, 'barbie smooth'), (5, 'outlined'), (6, 'nipple'), (7, 'full frontal')], default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
