# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0002_auto_20160715_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ovas',
            field=models.IntegerField(default=0),
        ),
    ]
