# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0003_show_ovas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='number',
        ),
        migrations.AddField(
            model_name='show',
            name='profanity',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'damn'), (2, 'cencored'), (3, 'Fuck')], default=0),
        ),
    ]
