# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0004_auto_20160715_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='movies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='os_intimacy',
            field=models.IntegerField(choices=[(0, 'indirect kiss/ handholding'), (1, 'light kissing'), (2, 'deep kissing/grope'), (3, 'sex')], default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='violence',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'cartoon'), (2, 'blood'), (3, 'realistic'), (4, 'extreme')], default=0),
        ),
    ]
