# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0007_auto_20160717_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200)),
                ('watch_order', models.CharField(max_length=500)),
            ],
        ),
    ]
