# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0008_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='morbid_images',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'unmarred dead'), (2, 'silhouetted dismemberment'), (3, 'dismemberment')], default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='gore',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'low'), (2, 'moderate'), (3, 'high'), (4, 'extreme')], default=0),
        ),
    ]
