# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0009_auto_20160801_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='moral_ambiguity',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'low'), (2, 'moderate'), (3, 'high'), (4, 'extreme')], default=0),
        ),
    ]
