# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0022_auto_20160821_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show'),
        ),
        migrations.AlterField(
            model_name='tag_relation',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show'),
        ),
    ]
