# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeupload', '0024_auto_20160821_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_relation',
            name='show',
        ),
        migrations.RemoveField(
            model_name='tag_relation',
            name='tag',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='animeupload.Show'),
        ),
        migrations.DeleteModel(
            name='Tag_relation',
        ),
    ]
